### ISSUE TITLE
Null pointer exception when no program is loaded

### ISSUE THREAD

**Issue by captainGeech42** [williamshowalter/revsync_ghidra#1]
After closing a program in Ghidra (9.1.2, jdk14 on Arch) and leaving the program idle in the background for a while, I got this exception:

```
Uncaught Exception! 
java.lang.NullPointerException
	at revsyncghidra.RevSyncGhidraPlugin.get_ea(RevSyncGhidraPlugin.java:75)
	at revsyncghidra.RevSyncGhidraPlugin.revsync_callback(RevSyncGhidraPlugin.java:306)
	at revsyncghidra.RevsyncClient$RevSub.onMessage(RevsyncClient.java:54)
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:144)
	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:117)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2816)
	at revsyncghidra.RevsyncClient$SubThread.run(RevsyncClient.java:150)
---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /usr/lib/jvm/java-14-openjdk
JVM Version: N/A 14.0.1
OS: Linux 5.7.7-arch1-1 amd64
Workstation: zw-pc-arch.localdomain
```

Looking at the [referenced line](https://github.com/williamshowalter/revsync_ghidra/blob/master/src/main/java/revsyncghidra/RevSyncGhidraPlugin.java#L75), I assume the problem is that `currentProgram` is null because there isn't a program loaded

**Comment by captainGeech42** [comment]
Spoke too soon, got the same exception/stack trace with a program loaded in and actively being analyzed

**Comment by williamshowalter** [comment]
I was able to replicate this behavior - it was a result of "programDeactivated()" only calling program.removeListener() and not ever unregistering the Redis client. Next time a closed program window received an updated comment or symbol it would still try to apply it, only for the previous program no longer existing. Master branch has the fix now and will be present in the next release. Thanks for submitting the report!
